comp:
    name : Mainzelcubing 2025
    shortname : Mainzelcubing 2025
    ID : Mainzelcubing2025
    loc : MZ
payment:
    paypalURLuptoAmount : https://www.paypal.com/paypalme/hugacuba/
    amountEUR : 19
mail : speedcubing.rlp.saar@gmail.com
setup:
    aftercomp : Yes
    awards : Yes
    sponsor : Yes
    unofficial : No
    gca : No
    logo : Yes
    logoPath : /Users/annikastein/Documents/Speedcubing/Competitions/Mainzelcubing25/Logo/MZC25_Logo_600.png
    multiStage : No
    stationsPerStage : 16
    assignRoles : s,r,j
orga:
    lostAndFound : something
    lostAndFoundGerman : etwas
    surveyLink : https://docs.google.com/forms/d/e/1FAIpQLScYT_TzeazzJl12yY5Jr_uBgMTJx4lYm-eutGIId08utpEg-g/viewform?usp=preview
    partCertLink : https:something
    systemJRS : scrambling and judging
    systemJRSGerman : Scrambling und Judging
    certificateBgPath : /Users/annikastein/Documents/Speedcubing/Competitions/Mainzelcubing25/Urkunden/certificate_MZC25.jpg
    fristStorno: Dienstag, 18. März 2025 um 08:00 MEZ
    deadlineStorno: Tuesday, March 18, 2025 at 8:00 AM GMT+1
