comp:
    name : Rheinland-Pfalz Open 2025
    shortname : RLP Open 2025
    ID : RheinlandPfalzOpen2025
mail : rlp-open@googlegroups.com
setup:
    aftercomp : Yes
    awards : Yes
    sponsor : Yes
    unofficial : Yes
