comp:
    name : Rheinland-Pfalz Open 2025
    shortname : RLP Open 2025
    ID : RheinlandPfalzOpen2025
    loc : Morbach
payment:
    paypalURLuptoAmount : https://www.paypal.com/paypalme/hugacuba/
    amountEUR : 19
mail : rlp-open@googlegroups.com
setup:
    aftercomp : Yes
    awards : Yes
    sponsor : Yes
    unofficial : Yes
    gca : No
    logo : Yes
    logoPath : /Users/annikastein/Documents/Speedcubing/Competitions/RLP25/Logo/Logo_600.png
    multiStage : Yes
    stationsPerStage : 18,18
    assignRoles : s,r,j
    feedMbfJudgesFrom: 333fm, minx, 444bf, 555bf
    feed444bfJudgesFrom: 333fm, minx, 333mbf
    feed555bfJudgesFrom: 333fm, minx, 333mbf
orga:
    lostAndFound : something,another thing
    lostAndFoundGerman : etwas,noch etwas
    surveyLink : https://docs.google.com/forms/d/e/1FAIpQLSdcI0mOLK8wx2CdpNtUTbpMKmwrz34ENe2Q45y8ngx97G7uDA/viewform?usp=preview
    partCertLink : https:something
    systemJRS : scrambling, running and judging
    systemJRSGerman : Scrambling, Running und Judging
    certificateBgPath : /Users/annikastein/Documents/Speedcubing/Competitions/RLP25/Urkunden/certificate_RLP25.jpg
    fristStorno: Montag, 26. Mai 2025 um 17:00 MESZ
    deadlineStorno: Monday, May 26, 2025 at 5:00 PM GMT+2
    openingDE: 'Am Freitag öffnet die Venue um 09:00 Uhr, am Samstag und Sonntag um 08:00 Uhr.'
    openingEN: 'On Friday, the venue will be open at 09:00, on Saturday and Sunday from 08:00.'
    tutorialWhenDE: 'am Samstag um 08:15 Uhr, am Sonntag um 08:10 Uhr'
    tutorialWhenEN: 'on Saturday at 08:15, on Sunday at 08:10'
