comp:
    name : Rheinland-Pfalz Open 2025
    shortname : RLP Open 2025
    ID : RheinlandPfalzOpen2025
    loc : Morbach
payment:
    paypalURLuptoAmount : https://www.paypal.com/paypalme/hugacuba/
    amountEUR : 19
mail : rlp-open@googlegroups.com
setup:
    aftercomp : Yes
    awards : Yes
    sponsor : Yes
    unofficial : Yes
    gca : Yes
    logo : Yes
    logoPath : /Users/annikastein/Documents/Speedcubing/Competitions/RLP25/Logo/Logo_600.png
    multiStage : Yes
orga:
    lostAndFound : something,another thing
    lostAndFoundGerman : etwas,noch etwas
    surveyLink : https://docs.google.com/forms/d/e/1FAIpQLSdcI0mOLK8wx2CdpNtUTbpMKmwrz34ENe2Q45y8ngx97G7uDA/viewform?usp=preview
    systemJRS : scrambling, running and judging
    systemJRSGerman : Scrambling, Running und Judging
