comp:
    name : Template 2025
    shortname : Template 2025
    ID : Template2025
    loc : MZ
payment:
    paypalURLuptoAmount : https://www.paypal.com/paypalme/hugacuba/
    amountEUR : 19
mail : speedcubing.rlp.saar@gmail.com
setup:
    aftercomp : Yes
    awards : Yes
    sponsor : Yes
    unofficial : No
    gca : No
    logo : Yes
    logoPath : /Users/annikastein/Documents/Speedcubing/Competitions/Mainzelcubing25/Logo/MZC25_Logo_600.png
    multiStage : No
    stationsPerStage : 10
    assignRoles : s,r,j
orga:
    lostAndFound : something
    lostAndFoundGerman : etwas
    surveyLink : https://docs.google.com/forms/d/e/1FAIpQLScYT_TzeazzJl12yY5Jr_uBgMTJx4lYm-eutGIId08utpEg-g/viewform?usp=preview
    partCertLink : https:something
    systemJRS : scrambling and judging
    systemJRSGerman : Scrambling und Judging
    certificateBgPath : /Users/annikastein/Documents/Speedcubing/Competitions/Mainzelcubing25/Urkunden/certificate_MZC25.jpg
    fristStorno: Montag, 26. Mai 2025 um 17:00 MESZ
    deadlineStorno: Monday, May 26, 2025 at 5:00 PM GMT+2
